/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './views/**/*.php',
    './layout.php',
    './index.php',
  ],
  safelist: [
    'card',
    'card--data',
    'card--module',
    'card--soft',
    'card--widget',
    'badge',
    'badge--positive',
    'badge--negative',
    'badge--neutral',
    'badge--warning',
    'badge--info',
    'badge--accent',
    'icon',
    'icon--16',
    'icon--24',
    'icon--32',
    'icon--64',
    'sidebar',
    'input',
    'textarea',
    'select',
    'checkbox',
    'radio',
    'switch',
    'upload',
    'search',
    'search--input',
    'password',
    'password--input',
    'otp',
    'otp--input',
    'datetime',
    'datetime--input',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
