/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './views/**/*.php',
    './layout.php',
    './index.php',
  ],
  safelist: [
    'card',
    'card--table',
    'card--module',
    'card--soft',
    'card--widget',
    'avatar',
    'avatar--sm',
    'avatar--lg',
    'badge',
    'badge--positive',
    'badge--negative',
    'badge--neutral',
    'badge--warning',
    'badge--info',
    'badge--accent',
    'icon',
    'icon--16',
    'icon--24',
    'icon--32',
    'icon--64',
    'sidebar',
    'input',
    'textarea',
    'select',
    'checkbox',
    'radio',
    'switch',
    'upload',
    'search',
    'search--input',
    'password',
    'password--input',
    'otp',
    'otp--input',
    'datetime',
    'datetime--input',
    'dropdown',
    'dropdown--left',
    'dropdown--right',
    'dropdown--open',
    'breadcrumb',
    'breadcrumb--compact',
    'empty',
    'empty--state',
    'alert',
    'alert--info',
    'alert--success',
    'alert--warning',
    'alert--danger',
    'alert--no-icon',
    'alert--dismissible',
    'alert--inline',
    'modal',
    'modal--sm',
    'modal--md',
    'modal--lg',
    'page',
    'page--header',
    'tabs',
    'tabs--compact',
    'toast',
    'toast--info',
    'toast--success',
    'toast--warning',
    'toast--danger',
    'toast--no-icon',
    'toast--dismissible',
    'tooltip',
    'tooltip--top',
    'tooltip--right',
    'tooltip--bottom',
    'tooltip--left',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
